config/routes.rb
Rails.application.routes.draw do
 root :to => 'pages#index'
 
 resources :owners, :accommodations

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/accommodation.rb
# == Schema Information
#
# Table name: accommodations
#
#  id         :integer          not null, primary key
#  owner_id   :integer
#  address    :text
#  image      :text
#  bedroom    :integer
#  bathroom   :integer
#  carpark    :integer
#  suburb     :string(255)
#  price      :float
#  detail     :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Accommodation < ActiveRecord::Base
	belongs_to :owner
end 

app/models/owner.rb
# == Schema Information
#
# Table name: owners
#
#  id              :integer          not null, primary key
#  firstname       :string(255)
#  lastname        :string(255)
#  contact         :integer
#  email           :string(255)
#  image           :text
#  created_at      :datetime
#  updated_at      :datetime
#  password_digest :string(255)
#

class Owner < ActiveRecord::Base
	has_secure_password
	has_many :accommodations
	validates :email, uniqueness: true
end 

app/controllers/accommodations_controller.rb
class AccommodationsController < ApplicationController 
	def index
		@accommodations = Accommodation.all
	end 

	def create 
		@accommodation = Accommodation.create accommodation_params
		@accommodation.owner_id = @current_user.id
		@accommodation.save
		redirect_to accommodation_path(@accommodation)
	end 

	def new 
		@accommodation = Accommodation.new
	end 

	def edit 
		@accommodation = Accommodation.find params[:id]
		#@accommodation.update accommodation_path
		#redirect_to accommodation_path(@accommodation)
	end 

	def show 
		@accommodation = Accommodation.find params[:id]
	end 

	def update
		@accommodation = Accommodation.find params[:id]
		@accommodation.update accommodation_params
		redirect_to accommodation_path
		

	end 

	def destroy 
		@accommodation = Accommodation.find params[:id]
		@accommodation.destroy
		redirect_to accommodations_path
	end 

	private 
	def accommodation_params
		params.require(:accommodation).permit(:image, :bedroom, :bathroom, :carpark, :address, :suburb, :price, :detail)
	end 
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
  protect_from_forgery with: :exception
  
  before_action :authenticate

  private
  def authenticate
  	@current_user = Owner.where(:id => session[:owner_id]).first
  	session[:owner_id] = nil unless @current_user.present?
  end 

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController 

	def index
		redirect_to root_path unless @current_user
		@owners = @current_user
	end 

	def new 
		@owner = Owner.new
	end 
	
	def create
		@owner = Owner.new owner_params
		if @owner.save
			session[:owner_id] = @owner.id
			redirect_to root_path
		else 
			render :new
		end
	end

	

	def edit 
		@owners = @current_user
		# @owner = Owner.find params[:id]
		# if @owner.update
		# 	session[:owner_id] = @owner_id
		# 	redirect_to owners_path
		# else
		# 	render :update
		# end 
	end

	def show 
		@owner = Owner.find params[:id]
	end

	def update 
		owner = @current_user
		owner.update owner_params
		redirect_to owner
		 
	end

	def destroy 
		@owner = Owner.find params[:id]
		@owner.destroy
		redirect_to owners_path
	end

	private 
	def owner_params
		params.require(:owner).permit(:firstname, :lastname, :contact, :email, :image, :password, :password_confirmation)
	end 
end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController 

	def index
		@accommodations = Accommodation.all
	end

	def show 
		@search = Accommodation.find params[:search]
	end 


end 

app/controllers/session_controller.rb
class SessionController < ApplicationController
	
	def new 
	end 

	def create
		owner = Owner.where(:email => params[:email]).first
		if owner.present? && owner.authenticate(params[:password])
			session[:owner_id] = owner.id
			redirect_to root_path
		else
			redirect_to login_path
		end 
	end
	
	def  destroy
		session[:owner_id] = nil
		redirect_to root_path
	end
end 

app/helpers/application_helper.rb
module ApplicationHelper
		def intellinav
		nav = ''
		if @current_user.present?
			nav += "<li> Welcome #{ @current_user.firstname } </li> "
			# nav += "<li>" + link_to('Edit profile', edit_owner_path) + "</li> "
			nav += "<li> #{ link_to('Sign Out', login_path, :method => :delete, :data => {:confirm => 'Are you sure?'}) }</li>"
		else 
			nav += "<li>#{ link_to('Join', new_owner_path) }</li> "
			nav += "<li>#{ link_to('Log In', login_path) }</li>"
		end
	end
end

app/views/accommodations/_form.html.erb
<div class="form">

	<%= form_for @accommodation do |f| %>
		<p>
			<%= f.label :image %>
			<%= f.url_field :image %>
		</p>

		<p>
			<%= f.label :bedroom %>
			<%= f.select :bedroom, options_for_select([['Select', 1],['ONE', 2],['TWO', 3],['THREE',4]],1) %>
		</p>

		<p>
			<%= f.label :bathroom %>
			<%= f.select :bathroom, options_for_select([['Select', 1],['ONE', 2],['TWO', 3],['THREE',4]],1) %>
		</p>

		<p>
			<%= f.label :carpark %>
			<%= f.select :carpark, options_for_select([['Select', 1],['ONE', 2],['TWO', 3],['THREE',4]],1) %>
		</p>

		<p>
			<%= f.label :address %>
			<%= f.text_field :address %>
		</p>

		<p>
			<%= f.label :suburb %>
			<%= f.text_field :suburb %>
		</p>

		<p>
			<%= f.label :price %>
			<%= f.text_field :price %>
		</p>

		<p>
			<%= f.label :detail %>
			<%= f.text_field :detail %>
		</p>

		<p>	<%= f.submit %></p>

	<% end %>

</div>

app/views/accommodations/edit.html.erb
<div class="form">
	<h4>Edit</h4> 
	
	<%= render :partial => 'form' %>

</div>

app/views/accommodations/index.html.erb
<div>
	<h4 class="title">Current listing</h4> 

<div class="list"> 
	<% @accommodations.each do |accommodation| %>

		<ul >
			<li><%= link_to(accommodation.address,accommodation_path(accommodation)) %></li>
			<li><%=  accommodation.suburb %></li>
		</ul>

	<% end %>
</div>


</div>

app/views/accommodations/new.html.erb
<div>
	<h4 class="title">List your property</h4> 
		<%= render :partial => 'form' %>
</div>

app/views/accommodations/show.html.erb
<div class="form">
	<div >
		<p> <%= @accommodation.address %></p>
	</div>
	<div class="image">
		
		<p><%= image_tag @accommodation.image, :class => 'avatar'%></p>
	</div>
	<div class="details">

		<ul>
			<li>Suburb: <%= @accommodation.suburb %></li>
			<li>Bedroom: <%= @accommodation.bedroom %></li>
			<li>Bathroom: <%= @accommodation.bathroom %></li>
			<li>Carpark: <%= @accommodation.carpark %></li>
			<li>Price: <%= @accommodation.price, value= number_to_currency(@accommodation.price) %></li>
			<li>Description: <%= @accommodation.detail %></li>
		</ul>
		<br>
		<% if @current_user && @current_user.id = @accommodation.owner_id %>
			<ul>
				<li><%= link_to 'Edit', edit_accommodation_path %></li>
				<li><%= link_to 'Delete', @accommodation, :method => :delete, :data => { :confirm => 'Are you sure?' } %></li>
			</ul>
		
			
		
		<% end %>	
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rentals</title>
  <link rel="stylesheet" type="css" href="http://fonts.googleapis.com/css?family=Raleway">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>


<body>

	<nav >
		<div class="main">
			<ul>
      			<li><%= link_to('Home', root_path) %></li>
      			<li><%= link_to('All Accommodation', accommodations_path) if @current_user %></li> 
	  			<li><%= link_to('Add Accommodation', new_accommodation_path)  if @current_user %></li> 
			</ul>
			<ul class="user_login">
      			<li><%== intellinav %></li>
    		</ul>
		</div>
	</nav>

	<div class="content">
		<%= yield %>
	</div>

</body>
</html>

app/views/owners/_form.html.erb
<nav class='wrapper'>
<div class="form">

	<% if @owner.errors.any? %>
		<% @owner.errors.full_messages.each do |err| %>
			<p><%= err %></p>
		<% end %>
	<% end %>

	<%= form_for @owner do |f| %>
		<p>
			<%= f.label :firstname %>
			<%= f.text_field :firstname %>
		</p> 

		<p>
			<%= f.label :lastname %>
			<%= f.text_field :lastname %>
		</p>

		<p>
			<%= f.label :contact %>
			<%= f.telephone_field :contact %>
		</p>

		<p>
			<%= f.label :email %>
			<%= f.email_field :email %>
		</p>

		<p>
			<%= f.label :image %>
			<%= f.url_field :image %>
		</p>
   	
   		<p>
     		<%= f.label :password %>
     		<%= f.password_field :password %>
   		</p>
   
   		<p>
    		<%= f.label :pasword_confirmation %>
     		<%= f.password_field :password_confirmation %>
   		</p>
	
		<%= f.submit %>

	<% end %>

</div>
</nav>

app/views/owners/edit.html.erb
<div class="form">
	<h4>Edit</h4> 
	
	<%= form_for @user do |f| %>
  	
  	<div>
    	<%= f.label :name %>
    	<%= f.text_field :name %>
  	</div>
  	
  	<div>
    	<%= f.label :email %>
    	<%= f.email_field :email %>
  	</div>
 
 		 <%= f.submit %>
	
	<% end %>

</div>

app/views/owners/index.html.erb
<div class="form">
	<h4><%= @owner.name %></h4>

 	<% @owners.each do |owner| %>
 	 	<ul>
  		 	<li><%= link_to(owner.firstname, owner) %></li>	
   		</ul>
   		
 	<% end %>

 </div>

app/views/owners/new.html.erb
<div>
	<h4 class="title">Sign Up</h4> 
	<%= render :partial => 'form' %>

</div>

app/views/owners/show.html.erb
<div class="form">
	<h3><%= @owner.name %></h3> 
	
	<p>
  		User since: <%= @owner.created_at.strftime '%B %m %Y' %>
  		<%= image_tag @owner.image %>
	</p>

</div>

app/views/pages/index.html.erb
<div >
	<h4 class='title'>Current listing</h4>
	<% @accommodations.each do |accommodation| %>

	<div class="front_image">
		<ul>
			<li><%=  image_tag accommodation.image, :class =>'avatar' %></li>	
		</ul>
	</div>
	
	<div class ="front_display">
		<ul>
			<li><%= link_to(accommodation.address,accommodation_path(accommodation)) %></li>
			<li><%=  accommodation.suburb %></li>
			<li><%= accommodation.price, value= number_to_currency(accommodation.price) %></li>
		</ul>
	</div>
	
	

	<% end %>

</div>

app/views/session/new.html.erb
<h4 class="title">Login</h4>	
<div class="form">

<%= form_tag '/login' do %>
  <%= label_tag :email %>
  <%= text_field_tag :email, nil, :autofocus => true %>
  <%= label_tag :password %>
  <%= password_field_tag :password, nil, :autofocus => true %>
  <%= submit_tag 'Login' %>
<% end %>

</div>